# Generated by Django 5.0.6 on 2026-09-09 12:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Should I accept the Senior Engineer offer at Company X?'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed context, motivations, and background.')),
                ('category', models.CharField(choices=[('CAREER', 'Career'), ('EDUCATION', 'Education'), ('FINANCE', 'Finance'), ('PERSONAL', 'Personal'), ('BUSINESS', 'Business'), ('TECHNOLOGY', 'Technology'), ('TRAVEL', 'Travel'), ('PURCHASE', 'Purchase'), ('RELATIONSHIPS', 'Relationships'), ('OTHER', 'Other')], default='CAREER', max_length=20)),
                ('importance', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('DECIDED', 'Decided'), ('OUTCOME_PENDING', 'Outcome Pending'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('deadline', models.DateField(blank=True, help_text='Target date to make the decision', null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('confidence_score', models.PositiveIntegerField(blank=True, help_text='Confidence level from 1% to 100%', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('decision_reasoning', models.TextField(blank=True, help_text='Why this option was chosen over alternatives')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='decisions.decision')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Criterion name', max_length=200)),
                ('weight', models.PositiveIntegerField(default=5, help_text='Importance weight (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('explanation', models.TextField(blank=True, help_text='Context on why this factor matters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='decisions.decision')),
            ],
            options={
                'ordering': ['-weight', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DecisionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Accept Offer A (Hybrid, San Francisco)'", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='decisions.decision')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='decision',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_in_decisions', to='decisions.decisionoption'),
        ),
        migrations.CreateModel(
            name='DecisionOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_status', models.CharField(choices=[('SUCCESSFUL', 'Successful'), ('NEUTRAL', 'Neutral'), ('UNSUCCESSFUL', 'Unsuccessful')], max_length=15)),
                ('actual_result', models.TextField(help_text='What actually happened in reality')),
                ('expected_result', models.TextField(blank=True, help_text='What was anticipated at decision time')),
                ('satisfaction_score', models.PositiveIntegerField(help_text='Retrospective satisfaction rating (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('outcome_date', models.DateField(help_text='Date when outcome was evaluated')),
                ('financial_impact', models.CharField(blank=True, help_text='Measurable financial or career outcome', max_length=200)),
                ('what_went_right', models.TextField(blank=True)),
                ('what_went_wrong', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='decisions.decision')),
            ],
        ),
        migrations.CreateModel(
            name='FactorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=5, help_text='Rating (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.CharField(blank=True, help_text='Brief rationale for this rating', max_length=255)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='decisions.decisionfactor')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factor_scores', to='decisions.decisionoption')),
            ],
        ),
        migrations.CreateModel(
            name='ProsCons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PRO', 'Pro'), ('CON', 'Con')], max_length=4)),
                ('text', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pros_cons', to='decisions.decisionoption')),
            ],
            options={
                'ordering': ['type', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['user', 'status'], name='decisions_d_user_id_5609a1_idx'),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['user', 'category'], name='decisions_d_user_id_75c6c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='factorscore',
            unique_together={('factor', 'option')},
        ),
    ]
